#
# Build stage
#
FROM maven:3.8.8-sapmachine-17 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -Pprod -DskipTests

#
# Package stage
#
FROM openjdk:17-alpine
COPY --from=build /home/app/target/banking-0.0.1-SNAPSHOT.jar /usr/local/lib/backend.jar
#Dinlenmesi gereken port
EXPOSE 8092
#Docker container çalıştırıldığında çalıştırılacak komut
ENTRYPOINT ["java","-jar","/usr/local/lib/backend.jar"]